cmake_minimum_required(VERSION 3.20.0 FATAL_ERROR)
project("easifemApp")
enable_language(Fortran)

    if (NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE Debug CACHE STRING "Build type" FORCE)
    endif()
    if(${CMAKE_Fortran_COMPILER_ID} STREQUAL "GNU" OR Fortran_COMPILER_NAME MATCHES "gfortran*")
list(APPEND FORTRAN_FLAGS "-ffree-form" "-ffree-line-length-none" "-std=f2008" "-fimplicit-none")
list(APPEND FORTRAN_FLAGS_RELEASE "-O3")
list(APPEND FORTRAN_FLAGS_DEBUG  "-fbounds-check" "-g" "-fbacktrace" "-Wextra" "-Wall" "-fprofile-arcs" "-ftest-coverage" "-Wimplicit-interface" )
endif()
if(${CMAKE_Fortran_COMPILER_ID} STREQUAL "Intel" OR Fortran_COMPILER_NAME MATCHES "ifort*")
list(APPEND FORTRAN_FLAGS "-r8" "-W1")
list(APPEND FORTRAN_FLAGS_RELEASE "-O3")
list(APPEND FORTRAN_FLAGS_DEBUG "-O0" "-traceback" "-g" "-debug all" "-check all" "-ftrapuv" "-warn" "nointerfaces")
endif()
if(${CMAKE_Fortran_COMPILER_ID} STREQUAL "XL" OR Fortran_COMPILER_NAME MATCHES "xlf*")
list(APPEND FORTRAN_FLAGS "-q64" "-qrealsize=8" "-qsuffix=f=f90:cpp=f90")
list(APPEND FORTRAN_FLAGS_RELEASE "-O3" "-qstrict")
list(APPEND FORTRAN_FLAGS_DEBUG "-O0" "-g" "-qfullpath" "-qkeepparm")
endif()
list(APPEND CMAKE_PREFIX_PATH  "/Users/easifem/.easifem/easifem/install/base"  "/Users/easifem/.easifem/easifem/install/fftw"  "/Users/easifem/.easifem/easifem/install/seepage"  "/Users/easifem/.easifem/easifem/install/superlu"  "/Users/easifem/.easifem/install/kernels/"  "/Users/easifem/.easifem/easifem/install/classes"  "/Users/easifem/.easifem/easifem/install/lis"  "/Users/easifem/.easifem/easifem/install/scalarWave"  "/Users/easifem/.easifem/easifem/install/lapack95"  "/Users/easifem/.easifem/easifem/install/oneDimElasticity"  "/Users/easifem/.easifem/easifem/install/sparsekit"  "/Users/easifem/.easifem/easifem/install/tomlf"  "/Users/easifem/.easifem/easifem/install/arpack"  "/Users/easifem/.easifem/easifem/install/diffusion" )
find_package("easifemBase")
add_executable(main.out  /Users/easifem/Library/CloudStorage/Dropbox/easifem/classes/src/modules/UserFunction/src/UserFunction_Class.F90)
target_link_libraries(main.out PRIVATE  easifemBase::easifemBase )
