[solid]
stressStrainModel = "linearElasticModel"

[solid.linearElasticModel]
name = "linearElasticModel"
elasticityType = "ISO"
poissonRatio = 0.1
youngsModulus = 1.0

[[solid.property]]
name = "massDensity"
returnType = "Scalar"
argType = "Constant"
value = 1.0

[[solid.property]]
name = "poissonRatio"
returnType = "Scalar"
argType = "Constant"
value = 2.0

[[solid.property]]
name = "youngsModulus"
returnType = "Scalar"
argType = "Constant"
value = 3.0
