[material]

[[material.property]]
returnType = "Scalar"
# returnType = "Vector"
# returnType = "Matrix"

numReturns = 1
# number of returns

argType = "Space"
# argType = "Constant"
# argType = "Space"
# argType = "Time"
# argType = "SpaceTime"

numArgs = 3
# number of arguments

luaScript = "./hello.lua"
# lua script

luaFunctionName = "hello"
# lua function

value = 1.0
# scalar value

# value= [1.0, 2.0, 3.0]
# vector value

# value= [
#   [1.0, 2.0, 3.0],
#   [4.0, 5.0, 6.0],
#   [7.0, 8.0, 9.0],
# ]
# matrix value

[[material.property]]
returnType = "Scalar"
argType = "Space"
# argType = "Constant"
# argType = "Space"
# argType = "Time"
# argType = "SpaceTime"
numArgs = 3
numReturns = 1
luaScript = "./hello.lua"
luaFunctionName = "hello"
value = 1.0
# value= [1.0, 2.0, 3.0]
# value= [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]
