[linSolver]
engine = "NATIVE_SERIAL"
solverName = "CG"
convergenceIn = "RESIDUAL"
convergenceType = "RELATIVE"
scale = "NONE"
maxIter = 1000
krylovSubspaceSize = 50
bicgstab_ell = 2
atol = 0.0000000099999999
rtol = 0.0000000099999999
relativeToRHS = false
initx_zeros = true
sor_omega = 1.8999999999999999
"precondition.option" = "NO_PRECONDITION"
"precondition.name" = "ILU"
"precondition.ilu.lfil" = 5
"precondition.ilu.mbloc" = 10
"precondition.ilu.fill" = 5
"precondition.ilu.droptol" = 0.0050000000000000
"precondition.ilu.permtol" = 0.1000000000000000
"precondition.ilu.alpha" = 1.0000000000000000
"precondition.hybrid.name" = "SOR"
"precondition.hybrid.maxIter" = 25
"precondition.hybrid.ell" = 2
"precondition.hybrid.restart" = 40
"precondition.hybrid.tol" = 0.0010000000474975
"precondition.hybrid.omega" = 1.5000000000000000
"precondition.is.m" = 3
"precondition.is.p_is_alpha" = 1.0000000000000000
"precondition.adds.iter" = 1
"precondition.adds.isAdditiveSchwarz" = true
"precondition.ssor.omega" = 1.0000000000000000
"precondition.sainv.drop" = 0.0500000007450581
"precondition.saamg.theta" = 0.0500000007450581
"precondition.saamg.unsym" = false
"precondition.iluc.drop" = 0.0500000007450581
"precondition.iluc.rate" = 5.0000000000000000
